# Generated by Django 5.1.6 on 2025-05-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('question_id', models.IntegerField()),
                ('answer', models.TextField()),
                ('submitted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'student_portal_studentexam',
                'managed': False,
            },
        ),
    ]
