# Generated by Django 5.1.6 on 2025-05-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentexam',
            options={},
        ),
    ]
