# Generated by Django 5.1.6 on 2025-04-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EligibleStudent',
        ),
        migrations.AddField(
            model_name='studentexam',
            name='feedback_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='feedback_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='feedback_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='marks_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='marks_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='marks_3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
